#!/usr/bin/env bash
player="ncspot"

class=$(playerctl --player="$player" metadata --format '{{lc(status)}}' 2>/dev/null)
icon=""

if [[ "$class" == "playing" ]]; then
  info=$(playerctl --player="$player" metadata --format '{{title}}' 2>/dev/null | sed -E 's/[-(].*//')
  if [[ ${#info} -gt 40 ]]; then
    info="${info:0:40}..."
  fi
  text="$info $icon"
elif [[ "$class" == "paused" ]]; then
  info=$(playerctl --player="$player" metadata --format '{{title}}' 2>/dev/null | sed -E 's/[-(].*//')
  if [[ ${#info} -gt 40 ]]; then
    info="${info:0:40}..."
  fi
  text=" $info $icon"
  else
    text=""



echo -e "{\"text\":\""$text"\", \"class\":\""$class"\"}"
